### ISSUE TITLE
Is it normal for aspects ctor to be called on every class injected with DesignedByContract?

### ISSUE THREAD

**Issue by georgiosd** [Pathoschild/DesignByContract#7]
Just noticed something strange while profiling my app with dotTrace 5.3 and tried to reproduce it.

With this code:

```
using System;
using Pathoschild.DesignByContract;

[assembly: DesignedByContract]

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Console.WriteLine(new Foo(null).DateTime);
            } catch(Exception) 
            {}
        }
    }

    public class Foo 
    {
        [NotNull]
        public string DateTime { get; set; }

        public Foo(string dateTime)
        {
        }
    }


}
```

It seems that an aspects ctor is called when the Foo ctor is called, just like it would be if you were inheriting from an object (which would be the aspect itself).

Is this normal? It doesn't seem to happen if I remove the NotNull attribute.

**Comment by Pathoschild** [comment]
Hey Georgios,

Yes, this is normal. A new aspect instance is created for every target to which it's applied (see _[Aspect Lifetime & Scope Part 1](http://www.postsharp.net/blog/post/Day-9-Aspect-Lifetime-Scope-Part-1)_ on the PostSharp blog). That's why the constructor is very simple — the analysis is performed during the build in the `CompileTimeInitialize` and `CompileTimeValidate` methods, and PostSharp deserializes the initialized attribute at runtime as needed.
